title: Jaidev Suresh
description: Personal encyclopedia of Jaidev Suresh
url: https://jaisur684.github.io
baseurl: ""

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
heading_anchors: true
nav_enabled: true

aux_links:
  "GitHub":
    - "https://github.com/jaisur684"

footer_content: "This site is a personal encyclopedia."

markdown: kramdown
